In [33]:
import json
import pandas as pd
import os
from datetime import datetime

In [34]:
df_main = pd.DataFrame()
df_main['bike_numbers'] = ''

In [35]:
def get_date(file):
    base = os.path.basename(file)
    clear_date = base.split('.')[0]
    date_time = datetime.strptime(clear_date, '%Y%m%d_%H%M%S')
    date = date_time.strftime("%d/%m/%Y, %H:%M:%S")
    return date

In [40]:
a = 1
path = os.getcwd()
#files = [os.path.join(path, data_file) for data_file in sorted(os.listdir(path))]
files = [data_file for data_file in sorted(os.listdir(path))]
path

'C:\\Users\\Maciej\\Documents\\Python\\inteligentne obliczenia\\Untitled Folder\\data\\rowery\\rowery'

In [37]:
filename_main = 'all_lokalization_of_bike.csv'
files_bike = files[3000:3025]
for file in files_bike:
    print(f"Odczytywanie pliku: {a} z {len(files_bike)}")
    a+=1
    d_T = get_date(file)
    with open(file) as f:
        all_data = json.load(f)
        f.close()
    try:
        #pozysikiwanie numerów rowerów z danych
        df = pd.DataFrame(all_data[0]['places'])
        df = df.assign(bike_numbers=df['bike_numbers'].str.split(',')).dropna(subset=['bike_numbers']).explode('bike_numbers')
        df = df.filter(['lat', 'lng', 'bike_numbers'])
        df[d_T] = df['lat'] + ',' + df['lng']  # zmienić na kolejne bases

        # zamiana kolumn bike_numbers na pierwszą i usunięcie
        cols = df.columns.tolist()
        cols.insert(0, cols.pop(cols.index('bike_numbers')))
        df = df.reindex(columns=cols)
        df = df.reset_index()
        df = df.drop(columns=['lat', 'lng', 'index'])
        df_main = pd.merge(df_main, df, on='bike_numbers', how='outer') # dopisywanie pliku do DataFrame main
        del df
    except:
        print(f"Nie można poprawnie odczytać pliku {file}")

print("Koniec wczytywania plików")
#df_main.to_csv(filename_main, encoding='utf-8', index=False)

Odczytywanie pliku: 1 z 25
Odczytywanie pliku: 2 z 25
Odczytywanie pliku: 3 z 25
Odczytywanie pliku: 4 z 25
Odczytywanie pliku: 5 z 25
Odczytywanie pliku: 6 z 25
Odczytywanie pliku: 7 z 25
Odczytywanie pliku: 8 z 25
Odczytywanie pliku: 9 z 25
Odczytywanie pliku: 10 z 25
Odczytywanie pliku: 11 z 25
Odczytywanie pliku: 12 z 25
Odczytywanie pliku: 13 z 25
Odczytywanie pliku: 14 z 25
Odczytywanie pliku: 15 z 25
Odczytywanie pliku: 16 z 25
Odczytywanie pliku: 17 z 25
Odczytywanie pliku: 18 z 25
Odczytywanie pliku: 19 z 25
Odczytywanie pliku: 20 z 25
Odczytywanie pliku: 21 z 25
Odczytywanie pliku: 22 z 25
Odczytywanie pliku: 23 z 25
Odczytywanie pliku: 24 z 25
Odczytywanie pliku: 25 z 25
Koniec wczytywania plików

In [38]:
df_main

,bike_numbers,"24/03/2018, 20:40:18","24/03/2018, 20:50:23","24/03/2018, 21:00:20","24/03/2018, 21:10:19","24/03/2018, 21:20:17","24/03/2018, 21:30:19","24/03/2018, 21:40:17","24/03/2018, 21:50:21","24/03/2018, 22:00:21",...,"24/03/2018, 23:10:20","24/03/2018, 23:20:18","24/03/2018, 23:30:18","24/03/2018, 23:40:18","24/03/2018, 23:50:21","25/03/2018, 00:00:23","25/03/2018, 00:10:18","25/03/2018, 00:20:18","25/03/2018, 00:30:20","25/03/2018, 00:40:22"
0,24886,"52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575",...,"52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575"
1,28601,"52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575",...,"52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575"
2,28478,"52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575",...,"52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575"
3,28308,"52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575",...,"52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575"
4,27450,"52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575",...,"52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575","52.296298,20.9583575"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4912,26459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,"52.1521429,21.0181224","52.1521429,21.0181224","52.1521429,21.0181224","52.1521429,21.0181224","52.1521429,21.0181224","52.1521429,21.0181224","52.1521429,21.0181224"
4913,29249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,"52.1521429,21.0181224","52.1521429,21.0181224","52.1521429,21.0181224","52.1521429,21.0181224","52.1521429,21.0181224","52.1521429,21.0181224","52.1521429,21.0181224"
4914,25471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"52.18648,21.02538","52.18648,21.02538","52.18648,21.02538"
4915,29349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"52.2223071,21.0907259","52.2223071,21.0907259","52.2223071,21.0907259"
4916,27854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"52.302617128435,21.058795452118"